server:
  port: 8180
  tomcat:
    min-spare-threads: 20
    max-threads: 100
  connection-timeout: 5000

spring:
  #指定运行环境
  profiles:
    active: dev

#日志配置
logging:
  config: classpath:log4j2-spring.yml