server:
  port: 8180
  tomcat:
    min-spare-threads: 20
    max-threads: 100
  connection-timeout: 5000



spring:
  #jpa配置
  jpa:
    show-sql: true
    database: mysql
  #mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.36.129:3306/family?characterEncoding=utf-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    # HikariCP连接池配置
    hikari:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
#redis配置
  redis:
    host: 192.168.137.240
    port: 6379
