spring:
  #指定运行环境
  profiles:
    active: dev
  #邮箱设置
  mail:
    host: smtp.mxhichina.com
    username: xxxxx@hsss.cn
    password: XXXXXX
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#日志配置
logging:
  config: classpath:log4j2.xml

#配置文件上传大小
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
#异步线程池配置
  threadpool:
    corePoolSize: 10
    maxPoolSize: 20
    queueCapacity: 200
    keepAliveSeconds: 60
    threadNamePrefix: taskExecutor-