version: '2'
services:
  mysql:
    image: ruihonghe/mysql:0.0.1-SNAPSHOT
    container_name: mysql
    restart: always
    networks:
      - test-network
    dns_search: .
    ports:
      - 3306:3306
  springboot:
    image: ruihonghe/springboot:0.0.1-SNAPSHOT
    container_name: springboot
    restart: always
    volumes:
      -  /etc/localtime:/etc/localtime
    networks:
      - test-network
    dns_search: .
    ports:
      - 8180:8180
    depends_on:
      - mysql
  nginx:
    image: ruihonghe/nginx:0.0.1-SNAPSHOT
    container_name: nginx
    restart: always
    networks:
      - test-network
    dns_search: .
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
      - springboot
  redis:
    image: ruihonghe/redis:0.0.1-SNAPSHOT
    container_name: redis
    restart: always
    networks:
        - test-network
    dns_search: .
    ports:
        - 6379:6379
  mongodb:
    image: ruihonghe/mongodb:0.0.1-SNAPSHOT
    container_name: mongodb
    restart: always
    networks:
       - test-network
    dns_search: .
    ports:
      - 27017:27017
#  neo4j:
#    image: ruihonghe/neo4j:0.0.1-SNAPSHOT
#    container_name: neo4j
#    restart: always
#    networks:
#      - test-network
#    dns_search: .
#    ports:
#      - 7474:7474
#      - 7687:7687
networks:
  test-network:
    external: false
